name: Docker Image Testing CI

on:
  push:
    branches:
      - dev

env:
  APP_NAME: qexo
  DOCKERHUB_REPO: abudulin/qexo

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Generate App Version
        run: echo APP_VERSION=`git rev-parse --short HEAD 2>/dev/null` >> $GITHUB_ENV
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: |
            linux/386
            linux/amd64
            linux/arm64
#            linux/ppc64le  # Too slow....
#            linux/s390x
#            linux/arm/v6
#            linux/arm/v7
          push: true
          build-args: |
            APP_NAME=${{ env.APP_NAME }}
            APP_VERSION=${{ env.APP_VERSION }}
          tags: |
            ${{ env.DOCKERHUB_REPO }}:testing
            ${{ env.DOCKERHUB_REPO }}:${{ env.APP_VERSION }}