name: Test Docker

on:
  workflow_dispatch:

env:
  APP_NAME: qexo
  DOCKERHUB_REPO: abudulin/qexo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: |
            linux/386
            linux/amd64
            linux/arm64
            linux/ppc64le
            linux/arm/v6
            linux/arm/v7
#            linux/s390x
          push: false
          build-args: |
            APP_NAME=${{ env.APP_NAME }}
          tags: |
            ${{ env.DOCKERHUB_REPO }}:testing